import { useState } from 'react';
import { Video, Loader2, Play, AlertCircle, Ghost } from 'lucide-react';
import { startVideoGeneration, getVideoStatus, type VideoJob } from '../lib/api';

interface VideoPlayerProps {
  emailContent: string;
  language: string;
}

export function VideoPlayer({ emailContent, language }: VideoPlayerProps) {
  const [status, setStatus] = useState<'idle' | 'generating' | 'ready' | 'error'>('idle');
  const [videoUrl, setVideoUrl] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [progress, setProgress] = useState(0);

  const generateVideo = async () => {
    setStatus('generating');
    setError(null);
    setProgress(0);

    try {
      // Start video generation
      const { job_id } = await startVideoGeneration(emailContent, language);

      // Poll for status
      let attempts = 0;
      const maxAttempts = 120; // 10 minutes max

      const pollInterval = setInterval(async () => {
        attempts++;
        setProgress(Math.min((attempts / maxAttempts) * 100, 95));

        try {
          const jobStatus: VideoJob = await getVideoStatus(job_id);

          if (jobStatus.status === 'completed' && jobStatus.video_url) {
            clearInterval(pollInterval);
            setVideoUrl(jobStatus.video_url);
            setStatus('ready');
            setProgress(100);
          } else if (jobStatus.status === 'failed') {
            clearInterval(pollInterval);
            setError(jobStatus.error || 'Video generation failed');
            setStatus('error');
          } else if (attempts >= maxAttempts) {
            clearInterval(pollInterval);
            setError('Video generation timed out');
            setStatus('error');
          }
        } catch (err) {
          console.error('Error polling video status:', err);
        }
      }, 5000); // Poll every 5 seconds

    } catch (err) {
      console.error('Error starting video generation:', err);
      setError('Failed to start video generation');
      setStatus('error');
    }
  };

  return (
    <div className="bg-gradient-to-br from-slate-800 to-slate-900 rounded-xl p-6 text-white">
      <div className="flex items-center gap-2 mb-4">
        <Ghost className="w-5 h-5 text-blue-400" />
        <h3 className="text-lg font-semibold">AI Avatar Video</h3>
      </div>

      {status === 'idle' && (
        <div className="text-center py-8">
          <div className="w-20 h-20 mx-auto mb-4 bg-slate-700 rounded-full flex items-center justify-center">
            <Video className="w-10 h-10 text-slate-400" />
          </div>
          <p className="text-slate-300 mb-4">
            Generate a video of an AI avatar reading the feedback email
          </p>
          <button
            onClick={generateVideo}
            className="flex items-center gap-2 mx-auto px-6 py-3 bg-blue-600 hover:bg-blue-700 rounded-lg font-medium transition-colors"
          >
            <Play className="w-4 h-4" />
            Generate Avatar Video
          </button>
          <p className="text-xs text-slate-500 mt-3">
            Takes 2-3 minutes to generate
          </p>
        </div>
      )}

      {status === 'generating' && (
        <div className="text-center py-8">
          <div className="w-20 h-20 mx-auto mb-4 bg-blue-600/20 rounded-full flex items-center justify-center">
            <Loader2 className="w-10 h-10 text-blue-400 animate-spin" />
          </div>
          <p className="text-slate-300 mb-2">Generating your video...</p>
          <p className="text-sm text-slate-400 mb-4">This may take 2-3 minutes</p>

          {/* Progress bar */}
          <div className="w-full max-w-xs mx-auto bg-slate-700 rounded-full h-2 overflow-hidden">
            <div
              className="h-full bg-blue-500 transition-all duration-500"
              style={{ width: `${progress}%` }}
            />
          </div>
          <p className="text-xs text-slate-500 mt-2">{Math.round(progress)}%</p>
        </div>
      )}

      {status === 'ready' && videoUrl && (
        <div>
          <video
            src={videoUrl}
            controls
            autoPlay
            className="w-full rounded-lg shadow-lg"
            style={{ maxHeight: '400px' }}
          >
            Your browser does not support the video tag.
          </video>
          <p className="text-xs text-slate-500 mt-3 text-center">
            Video generated by HeyGen AI
          </p>
        </div>
      )}

      {status === 'error' && (
        <div className="text-center py-8">
          <div className="w-20 h-20 mx-auto mb-4 bg-red-600/20 rounded-full flex items-center justify-center">
            <AlertCircle className="w-10 h-10 text-red-400" />
          </div>
          <p className="text-red-400 mb-2">Video generation failed</p>
          <p className="text-sm text-slate-400 mb-4">{error}</p>
          <button
            onClick={generateVideo}
            className="px-6 py-2 bg-slate-700 hover:bg-slate-600 rounded-lg font-medium transition-colors"
          >
            Try Again
          </button>
        </div>
      )}
    </div>
  );
}
